accounts:
  - platform: x
    username: "Daisy1004"
    name: "Daisy"

  - platform: x
    username: "berryxgxm"
    name: "Berry"

  - platform: x
    username: "lilithcoser"
    name: "Lilith Coser"
